### ISSUE TITLE
Road to 1.1

### ISSUE THREAD

**Issue by Alcha** [Paranoid-Devs/Tron#17]
# TODO
Here lies a list of things I'd like to accomplish before releasing the 1.1 version of Tron:

- [ ] Fix issues #16, #15, #14, and #13.
- [ ] Add birthday notification support for servers
- [ ] Add setup functionality to Tron when joining a new server
- [x] Add better method for handling beta/production environments - 0fea568
